[package]
name = "cryptography_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 = "0.30.0"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]
